Models/Client.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace Contract_Administrator.Models
{
    /// <summary>
    /// Model pro tabulku Klientů.
    /// </summary>
    public class Client
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Toto pole je povinné"), NotNull]
        [DisplayName("Jméno")]
        public string FirstName { get; set; } = "";

        [Required(ErrorMessage = "Toto pole je povinné"), NotNull]
        [DisplayName("Příjmení")]
        public string LastName { get; set; } = "";
        [Required(ErrorMessage = "Toto pole je povinné"), NotNull]
        [EmailAddress(ErrorMessage = "Neplatná emailová adresa.")]
        [DisplayName("Email")]
        public string Email { get; set; } = "";
        [Required(ErrorMessage = "Toto pole je povinné"), NotNull]
        [Phone(ErrorMessage = "Nasprávné telefonní číslo.")]
        [DisplayName("Telefonní číslo")]
        public string TelNumber { get; set; }
        [Required(ErrorMessage = "Toto pole je povinné"), NotNull]
        [DisplayName("Rodné číslo")]
        public string PersonalIdNum { get; set; }
        [Required, NotNull]
        [Range(0, 130, ErrorMessage = "Nepltná hodnota věku.")]
        [DisplayName("Věk")]
        public int Age { get; set; }
        [NotNull]
        [DisplayName("Uzavřené Smlouvy")]
        public ICollection<Contract>? Contracts { get; set; } = new List<Contract>();

    }

    
}

Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Contract_Administrator.Data;
using Contract_Administrator.Models;
using Contract_Administrator.Interfaces;
using Contract_Administrator.Repository;

namespace Contract_Administrator.Controllers
{
    public class ClientsController : Controller
    {
        private readonly IClientRepository _clientRepository;

        public ClientsController(IClientRepository clientRepository)
        {
            _clientRepository = clientRepository;
        }

        /// <summary>
        /// Zobrazuje view s přehledem klientů
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            return View(await _clientRepository.GetAll());
        }

        /// <summary>
        /// Zobrazuje view s podrobnostmi zvoleného klienta
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int id)
        {
            var client = await _clientRepository.GetByIdWithContractsAsync(id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        /// <summary>
        /// Zobrazuje view pro vytvoření klienta.
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            return View();
        }
        
        /// <summary>
        /// Ukládá záznam o vytvořeného klienta do databáze.
        /// </summary>
        /// <param name="client"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Client client)
        {
            if (!ModelState.IsValid)
            {
                return View(client);
            }
            _clientRepository.Add(client);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Zobrazuje view pro editaci klienta.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Edit(int id)
        {
            var client = await _clientRepository.GetByIdAsync(id);
            if (client == null) return NotFound();
            return View(client);
        }

        /// <summary>
        /// Ukládá upravená data o klientovi do databáze.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="client"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Client client)
        {
            if (id != client.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _clientRepository.Update(client);
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }
                return RedirectToAction("Index");
            }
            return View(client);
        }

        /// <summary>
        /// Zobrazí potvrzovací view před odstraněním klienta.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Delete(int id)
        {

            var client = await _clientRepository.GetByIdAsync(id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        /// <summary>
        /// Odstraní klienta podle id.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = await _clientRepository.GetByIdAsync(id);
            if (client != null)
            {
                _clientRepository.Delete(client);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/ContractsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Contract_Administrator.Data;
using Contract_Administrator.Models;
using NuGet.Protocol.Core.Types;
using System.Xml;
using System.Data;
using Microsoft.Extensions.Logging;
using Contract_Administrator.Interfaces;
using Contract_Administrator.ViewModels;
using System.Diagnostics.Contracts;
using Contract = Contract_Administrator.Models.Contract;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace Contract_Administrator.Controllers
{
    public class ContractsController : Controller
    {
        private readonly IContractRepository _contractRepository;
        private readonly IClientRepository _clientRepository;
        private readonly IAdviserRepository _adviserRepository;
        private readonly ApplicationDbContext _context;

        public ContractsController(ApplicationDbContext context, IContractRepository contractRepository, IClientRepository clientRepository, IAdviserRepository adviserRepository)
        {
            _contractRepository = contractRepository;
            _clientRepository = clientRepository;
            _adviserRepository = adviserRepository;
            _context = context;
        }

        /// <summary>
        /// Zobrazuje tabulku s přehledem smluv.
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            return View(await _contractRepository.GetAll());
        }

        /// <summary>
        /// Zobrazuje podrobnosti smlouvy podle id.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int id)
        {
            var contract = await _contractRepository.GetByIdWithAdvisersAndClientsAsync(id);
            if (contract == null)
            {
                return NotFound();
            }

            return View(contract);
        }

        /// <summary>
        /// Zobrazuje view pro přidání nové smlouvy do databáze.
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Create()
        {
            // vytvoření viewmodelu
            var viewModel = new ContractViewModel();
            SelectList client = new SelectList(_context.Client.ToList(), "Id", "LastName");
            SelectList adviser = new SelectList(_context.Adviser.ToList(), "Id", "LastName");
            viewModel.Clients = client;
            viewModel.Advisers = adviser;

            return View(viewModel);
        }

        /// <summary>
        /// Ukládá data nově vytvořené slmouvy do databáze
        /// </summary>
        /// <param name="contract"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Contract contract)
        {
            ModelState.Remove("contract.Client");
            if (!ModelState.IsValid) // ověření platnosti
            {
                var viewModel = new ContractViewModel();
                SelectList client = new SelectList(_context.Client.ToList(), "Id", "LastName");
                SelectList adviser = new SelectList(_context.Adviser.ToList(), "Id", "LastName");
                viewModel.Clients = client;
                viewModel.Advisers = adviser;
                return View(viewModel);
            }
            // vytvoření smlouvy
            _contractRepository.Add(contract);

            // propojení smlouvy a poradce
            var contractAdviser2 = new ContractAdviser
            {
                ContractId = contract.Id,
                AdviserId = contract.ContractAdmin,
                IsAdmin = true,
            };
            _context.ContractAdvisers.Add(contractAdviser2);

            foreach (var adviserId in contract.AdviserId)
            {
                var existingRelation = await _context.ContractAdvisers.FirstOrDefaultAsync(ca => ca.ContractId == contract.Id && ca.AdviserId == adviserId);
                if (existingRelation == null && (adviserId != contract.ContractAdmin))
                {
                    var contractAdviser = new ContractAdviser
                    {
                        ContractId = contract.Id,
                        AdviserId = adviserId,
                        IsAdmin = false,
                    };
                    _context.ContractAdvisers.Add(contractAdviser);
                }
            }
            await _context.SaveChangesAsync();

            // propojení klienta a smlouvy
            contract.Client = await _clientRepository.GetByIdAsync(contract.ClientId);

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Zobrazuje pohled pro editaci zvolené smlouvy.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Edit(int id)
        {
            var contract = await _contractRepository.GetByIdAsync(id);
            SelectList client = new SelectList(_context.Client.ToList(), "Id", "LastName", contract.ClientId);
            SelectList contractAdmin = new SelectList(_context.Adviser.ToList(), "Id", "LastName", contract.ContractAdmin);
            SelectList adviser = new SelectList(_context.Adviser.ToList(), "Id", "LastName", contract.AdviserId);
            // viewmodel
            var viewModel = new ContractViewModel
            {
                Clients = client,
                ContractAdmin = contractAdmin,
                Advisers = adviser,
                Contract = contract
            };
            return View(viewModel);
        }

        /// <summary>
        /// ukládá upravené data o smlouvě do databáze. 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="contract"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,ContractViewModel viewModel)
        {

            if (id != viewModel.Contract.Id)
            {
                return NotFound();
            }

            ModelState.Remove("contract.Client");
            ModelState.Remove("File");
            ModelState.Remove("Institution");
            if (!ModelState.IsValid)
            {
                var contract = await _contractRepository.GetByIdAsync(id);

                SelectList client = new SelectList(_context.Client.ToList(), "Id", "LastName", contract.ClientId);
                SelectList contractAdmin = new SelectList(_context.Adviser.ToList(), "Id", "LastName", contract.ContractAdmin);
                SelectList adviser = new SelectList(_context.Adviser.ToList(), "Id", "LastName", contract.AdviserId);
                viewModel.Clients = client;
                viewModel.ContractAdmin = contractAdmin;
                viewModel.Advisers = adviser;
                viewModel.Contract = contract;
                return View(viewModel);
            }
            _contractRepository.Update(viewModel.Contract);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Zobrazuje potvrzovací view před odstraněním smllouvy.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Delete(int id)
        {
            var contract = await _contractRepository.GetByIdAsync(id);
            if (contract == null)
            {
                return NotFound();
            }

            return View(contract);
        }

        /// <summary>
        /// Odstraní záznam o smlouvě z databáze.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contract = await _contractRepository.GetByIdAsync(id);
            if (contract != null)
            {
                _contractRepository.Delete(contract);
            }

            return RedirectToAction("Index");
        }

        private bool ContractExists(int id)
        {
            return _context.Contract.Any(e => e.Id == id);
        }
    }
}

Views/Clients/Create.cshtml
@model Contract_Administrator.Models.Client

@{
    ViewData["Title"] = "Nový klient";
}

<div class="row">
    <h3 class="col-lg">Nový klient</h3>
    <a asp-action="Index" class="col-lg-auto d-none d-lg-flex">Zpět na přehled</a>
</div>
<hr />

<div class="row">
    <form method="post" asp-action="Create" class="container-fluid">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">
            <div class="form-group my-3 col-lg-6">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group my-3 col-lg-6">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group my-3 col-lg-6">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group my-3 col-lg-6">
                <label asp-for="TelNumber" class="control-label"></label>
                <input asp-for="TelNumber" class="form-control" />
                <span asp-validation-for="TelNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group my-3 col-lg-6">
                <label asp-for="PersonalIdNum" class="control-label"></label>
                <input asp-for="PersonalIdNum" class="form-control" />
                <span asp-validation-for="PersonalIdNum" class="text-danger"></span>
            </div>
            <div class="form-group my-3 col-lg-6">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group my-3 col-lg-12">
                <input type="submit" value="Přidat klienta" class="btn btn-primary text-light" />
                <a asp-action="Index" class="btn btn-close-white">Zpět</a>
            </div>
        </div>
    </form>
</div>

Views/Clients/Delete.cshtml
@model Contract_Administrator.Models.Client

@{
    ViewData["Title"] = "Odstranění klienta";
}

<div class="row">
    <div class="col-lg">
        <h3 class="my-3">Opravdu chcete odstranit klienta @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)?</h3>
    </div>
    <a asp-action="Index" class="col-lg-auto d-none d-lg-flex">Zpět na přehled</a>
    <hr />
</div>

<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TelNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TelNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonalIdNum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonalIdNum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Smazat" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-close-white">Zpět</a>
    </form>
</div>

Views/Clients/Details.cshtml
@model Contract_Administrator.Models.Client

@{
    ViewData["Title"] = "Podrobnosti klienta";
}

<div class="row">
    <div class="col-lg">
        <h1>@Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</h1>
        <h4>Poradce</h4>
    </div>
    <a asp-action="Index" class="col-lg-auto d-none d-lg-flex">Zpět na přehled</a>
    <hr />
</div>

<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TelNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TelNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonalIdNum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonalIdNum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Contracts)
        </dt>
        <dd class="col-sm-10">
            @foreach (var item in Model.Contracts)
            {
                <a asp-controller="Contracts" asp-action="Details" asp-route-id="@item.Id">
                    Smlouva @item.Id<br />
                </a>
            }
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-secondary btn-outline-secondary">Upravit</a>
    <a asp-action="Index" class="btn btn-close-white">Zpět</a>
</div>

Views/Clients/Edit.cshtml
@model Contract_Administrator.Models.Client

@{
    ViewData["Title"] = "Změna klienta";
}

<div class="row">
    <div class="col-lg">
        <h1>Klient - změna</h1>
    </div>
    <a asp-action="Index" class="col-lg-auto d-none d-lg-flex">Zpět na přehled</a>
    <hr />
</div>

<div class="row">
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="row">
            <div class="form-group my-3 col-lg-6">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group my-3 col-lg-6">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group my-3 col-lg-6">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group my-3 col-lg-6">
                <label asp-for="TelNumber" class="control-label"></label>
                <input asp-for="TelNumber" class="form-control" />
                <span asp-validation-for="TelNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group my-3 col-lg-6">
                <label asp-for="PersonalIdNum" class="control-label"></label>
                <input asp-for="PersonalIdNum" class="form-control" />
                <span asp-validation-for="PersonalIdNum" class="text-danger"></span>
            </div>
            <div class="form-group my-3 col-lg-6">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group my-3 col-lg-12">
                <input type="submit" value="Uložit změny" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-close-white">Zpět</a>

            </div>
        </div>
    </form>
</div>

Views/Clients/Index.cshtml
@model IEnumerable<Contract_Administrator.Models.Client>

@{
    ViewData["Title"] = "Klienti";
}

<h1>Přehled klientů</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TelNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PersonalIdNum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                <a asp-action="Create" class="btn btn-primary mx-6">Nový klient</a>
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TelNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PersonalIdNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Upravit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Podrobnosti</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Smazat</a>
            </td>
        </tr>
}
    </tbody>
</table>
<p>
    <a asp-action="Create" class="btn btn-secondary btn-outline-secondary text-dark">Nový klient</a>
</p>