Controllers/AdvisersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Contract_Administrator.Data;
using Contract_Administrator.Models;
using Contract_Administrator.Interfaces;

namespace Contract_Administrator.Controllers
{
    public class AdvisersController : Controller
    {
        private readonly IAdviserRepository _adviserRepository;

        public AdvisersController(IAdviserRepository adviserRepository)
        {
            _adviserRepository = adviserRepository;
        }

        /// <summary>
        /// Spuští přehled poradců.
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            return View(await _adviserRepository.GetAll());
        }

        /// <summary>
        /// Zobrazuje View s detaily poradců.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int id)
        {
            var adviser = await _adviserRepository.GetByIdAsync(id);
            if (adviser == null)
            {
                return NotFound();
            }

            return View(adviser);
        }

        /// <summary>
        /// Zobrazuje View pro vytvoření poradce.
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            return View();
        }
        
        /// <summary>
        /// Ukládá data nově vytvořeného poradce do databáze.
        /// </summary>
        /// <param name="adviser"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Email,TelNumber,PersonalIdNum,Age")] Adviser adviser)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            _adviserRepository.Add(adviser);
            return RedirectToAction("Index");
        }
        
        /// <summary>
        /// Zobrazuje view pro editaci poradce.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Edit(int id)
        {
            var adviser = await _adviserRepository.GetByIdAsync(id);
            if (adviser == null) return NotFound();
            return View(adviser);
        }

        /// <summary>
        /// Ukládá upraveného klienta do databáze.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="adviser"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Email,TelNumber,PersonalIdNum,Age")] Adviser adviser)
        {
            if (id != adviser.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _adviserRepository.Update(adviser);
                }
                catch (DbUpdateConcurrencyException)
                {
                        return NotFound();
                }
                return RedirectToAction("Index");
            }
            return View(adviser);
        }

        /// <summary>
        /// Zobrazuje potvrzovací view pro smazání poradce.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Delete(int id)
        {
            var adviser = await _adviserRepository.GetByIdAsync(id);
            if (adviser == null)
            {
                return NotFound();
            }

            return View(adviser);
        }

        /// <summary>
        /// Maže záznam o poradci podle id.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var adviser = await _adviserRepository.GetByIdAsync(id);
            if (adviser != null)
            {
                _adviserRepository.Delete(adviser);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Contract_Administrator.Data;
using Contract_Administrator.Models;
using Contract_Administrator.Interfaces;
using Contract_Administrator.Repository;

namespace Contract_Administrator.Controllers
{
    public class ClientsController : Controller
    {
        private readonly IClientRepository _clientRepository;

        public ClientsController(IClientRepository clientRepository)
        {
            _clientRepository = clientRepository;
        }

        /// <summary>
        /// Zobrazuje view s přehledem klientů
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            return View(await _clientRepository.GetAll());
        }

        /// <summary>
        /// Zobrazuje view s podrobnostmi zvoleného klienta
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int id)
        {
            var client = await _clientRepository.GetByIdWithContractsAsync(id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        /// <summary>
        /// Zobrazuje view pro vytvoření klienta.
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            return View();
        }
        
        /// <summary>
        /// Ukládá záznam o vytvořeného klienta do databáze.
        /// </summary>
        /// <param name="client"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Client client)
        {
            if (!ModelState.IsValid)
            {
                return View(client);
            }
            _clientRepository.Add(client);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Zobrazuje view pro editaci klienta.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Edit(int id)
        {
            var client = await _clientRepository.GetByIdAsync(id);
            if (client == null) return NotFound();
            return View(client);
        }

        /// <summary>
        /// Ukládá upravená data o klientovi do databáze.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="client"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Client client)
        {
            if (id != client.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _clientRepository.Update(client);
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }
                return RedirectToAction("Index");
            }
            return View(client);
        }

        /// <summary>
        /// Zobrazí potvrzovací view před odstraněním klienta.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Delete(int id)
        {

            var client = await _clientRepository.GetByIdAsync(id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        /// <summary>
        /// Odstraní klienta podle id.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = await _clientRepository.GetByIdAsync(id);
            if (client != null)
            {
                _clientRepository.Delete(client);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/ContractsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Contract_Administrator.Data;
using Contract_Administrator.Models;
using NuGet.Protocol.Core.Types;
using System.Xml;
using System.Data;
using Microsoft.Extensions.Logging;
using Contract_Administrator.Interfaces;
using Contract_Administrator.ViewModels;
using System.Diagnostics.Contracts;
using Contract = Contract_Administrator.Models.Contract;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace Contract_Administrator.Controllers
{
    public class ContractsController : Controller
    {
        private readonly IContractRepository _contractRepository;
        private readonly IClientRepository _clientRepository;
        private readonly IAdviserRepository _adviserRepository;
        private readonly ApplicationDbContext _context;

        public ContractsController(ApplicationDbContext context, IContractRepository contractRepository, IClientRepository clientRepository, IAdviserRepository adviserRepository)
        {
            _contractRepository = contractRepository;
            _clientRepository = clientRepository;
            _adviserRepository = adviserRepository;
            _context = context;
        }

        /// <summary>
        /// Zobrazuje tabulku s přehledem smluv.
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            return View(await _contractRepository.GetAll());
        }

        /// <summary>
        /// Zobrazuje podrobnosti smlouvy podle id.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int id)
        {
            var contract = await _contractRepository.GetByIdWithAdvisersAndClientsAsync(id);
            if (contract == null)
            {
                return NotFound();
            }

            return View(contract);
        }

        /// <summary>
        /// Zobrazuje view pro přidání nové smlouvy do databáze.
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Create()
        {
            // vytvoření viewmodelu
            var viewModel = new ContractViewModel();
            SelectList client = new SelectList(_context.Client.ToList(), "Id", "LastName");
            SelectList adviser = new SelectList(_context.Adviser.ToList(), "Id", "LastName");
            viewModel.Clients = client;
            viewModel.Advisers = adviser;

            return View(viewModel);
        }

        /// <summary>
        /// Ukládá data nově vytvořené slmouvy do databáze
        /// </summary>
        /// <param name="contract"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Contract contract)
        {
            ModelState.Remove("contract.Client");
            if (!ModelState.IsValid) // ověření platnosti
            {
                var viewModel = new ContractViewModel();
                SelectList client = new SelectList(_context.Client.ToList(), "Id", "LastName");
                SelectList adviser = new SelectList(_context.Adviser.ToList(), "Id", "LastName");
                viewModel.Clients = client;
                viewModel.Advisers = adviser;
                return View(viewModel);
            }
            // vytvoření smlouvy
            _contractRepository.Add(contract);

            // propojení smlouvy a poradce
            var contractAdviser2 = new ContractAdviser
            {
                ContractId = contract.Id,
                AdviserId = contract.ContractAdmin,
                IsAdmin = true,
            };
            _context.ContractAdvisers.Add(contractAdviser2);

            foreach (var adviserId in contract.AdviserId)
            {
                var existingRelation = await _context.ContractAdvisers.FirstOrDefaultAsync(ca => ca.ContractId == contract.Id && ca.AdviserId == adviserId);
                if (existingRelation == null && (adviserId != contract.ContractAdmin))
                {
                    var contractAdviser = new ContractAdviser
                    {
                        ContractId = contract.Id,
                        AdviserId = adviserId,
                        IsAdmin = false,
                    };
                    _context.ContractAdvisers.Add(contractAdviser);
                }
            }
            await _context.SaveChangesAsync();

            // propojení klienta a smlouvy
            contract.Client = await _clientRepository.GetByIdAsync(contract.ClientId);

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Zobrazuje pohled pro editaci zvolené smlouvy.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Edit(int id)
        {
            var contract = await _contractRepository.GetByIdAsync(id);
            SelectList client = new SelectList(_context.Client.ToList(), "Id", "LastName", contract.ClientId);
            SelectList contractAdmin = new SelectList(_context.Adviser.ToList(), "Id", "LastName", contract.ContractAdmin);
            SelectList adviser = new SelectList(_context.Adviser.ToList(), "Id", "LastName", contract.AdviserId);
            // viewmodel
            var viewModel = new ContractViewModel
            {
                Clients = client,
                ContractAdmin = contractAdmin,
                Advisers = adviser,
                Contract = contract
            };
            return View(viewModel);
        }

        /// <summary>
        /// ukládá upravené data o smlouvě do databáze. 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="contract"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,ContractViewModel viewModel)
        {

            if (id != viewModel.Contract.Id)
            {
                return NotFound();
            }

            ModelState.Remove("contract.Client");
            ModelState.Remove("File");
            ModelState.Remove("Institution");
            if (!ModelState.IsValid)
            {
                var contract = await _contractRepository.GetByIdAsync(id);

                SelectList client = new SelectList(_context.Client.ToList(), "Id", "LastName", contract.ClientId);
                SelectList contractAdmin = new SelectList(_context.Adviser.ToList(), "Id", "LastName", contract.ContractAdmin);
                SelectList adviser = new SelectList(_context.Adviser.ToList(), "Id", "LastName", contract.AdviserId);
                viewModel.Clients = client;
                viewModel.ContractAdmin = contractAdmin;
                viewModel.Advisers = adviser;
                viewModel.Contract = contract;
                return View(viewModel);
            }
            _contractRepository.Update(viewModel.Contract);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Zobrazuje potvrzovací view před odstraněním smllouvy.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Delete(int id)
        {
            var contract = await _contractRepository.GetByIdAsync(id);
            if (contract == null)
            {
                return NotFound();
            }

            return View(contract);
        }

        /// <summary>
        /// Odstraní záznam o smlouvě z databáze.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contract = await _contractRepository.GetByIdAsync(id);
            if (contract != null)
            {
                _contractRepository.Delete(contract);
            }

            return RedirectToAction("Index");
        }

        private bool ContractExists(int id)
        {
            return _context.Contract.Any(e => e.Id == id);
        }
    }
}

Views/Contracts/Create.cshtml
@model Contract_Administrator.ViewModels.ContractViewModel

@{
    ViewData["Title"] = "Nová smlouva";
}

<div class="row">
    <h3 class="col-lg">Nová smlouva</h3>
    <a asp-action="Index" class="col-lg-auto d-none d-lg-flex">Zpět na přehled</a>
</div>
<hr />

<div class="row">
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">
            <div class="form-group col-lg-6 my-3">
                <label asp-for="Contract.RegistrationNumber" class="control-label"></label>
                <input asp-for="Contract.RegistrationNumber" class="form-control" />
                <span asp-validation-for="Contract.RegistrationNumber" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-6 my-3">
                <label asp-for="Contract.Institution" class="control-label"></label>
                <input asp-for="Contract.Institution" class="form-control" />
                <span asp-validation-for="Contract.Institution" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-lg-6 my-3">
                <label asp-for="Contract.ConclusionDate" class="control-label"></label>
                <input asp-for="Contract.ConclusionDate" class="form-control" />
                <span asp-validation-for="Contract.ConclusionDate" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-6 my-3">
                <label asp-for="Contract.ValidityDate" class="control-label"></label>
                <input asp-for="Contract.ValidityDate" class="form-control" />
                <span asp-validation-for="Contract.ValidityDate" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-lg-6 my-3">
                <label asp-for="Contract.ExpirationDate" class="control-label"></label>
                <input asp-for="Contract.ExpirationDate" class="form-control" />
                <span asp-validation-for="Contract.ExpirationDate" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-6 my-3">
                <label asp-for="Contract.ClientId" class="control-label"></label>
                <select asp-for="Contract.ClientId" class="form-control" asp-items="Model.Clients">
                    <option>-- Nevybráno --</option>
                </select>
                <span asp-validation-for="Contract.ClientId" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-lg-6 my-3">
                <label asp-for="Contract.ContractAdmin" class="control-label"></label>
                <select asp-for="Contract.ContractAdmin" class="form-control" asp-items="Model.Advisers">
                    <option>-- Nevybráno --</option>
                </select>
                <span asp-validation-for="Contract.ContractAdmin" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-6 my-3">
                <label asp-for="Contract.AdviserId" class="control-label"></label>
                <select asp-for="Contract.AdviserId" class="form-control" asp-items="Model.Advisers"></select>
                <span asp-validation-for="Contract.AdviserId" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-lg-6 my-3">
                <label asp-for="Contract.File" class="control-label"></label>
                <input asp-for="Contract.File" class="form-control" />
                <span asp-validation-for="Contract.File" class="text-danger"></span>

            </div>
        </div>
        <div class="row">
            <div class="form-group my-3 col-lg-12">
                <input type="submit" value="Přidat poradce" class="btn btn-primary text-light" />
                <a asp-action="Index" class="btn btn-close-white">Zpět</a>
            </div>
        </div>
    </form>
</div>

Views/Contracts/Delete.cshtml
@model Contract_Administrator.Models.Contract

@{
    ViewData["Title"] = "Odstranění smlouvy";
}

<div class="row">
    <div class="col-lg">
        <h3 class="my-3">Opravdu chcete odstranit smlouvu @Html.DisplayFor(model => model.RegistrationNumber)</h3>
    </div>
    <a asp-action="Index" class="col-lg-auto d-none d-lg-flex">Zpět na přehled</a>
    <hr />
</div>

<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegistrationNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Institution)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Institution)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContractAdmin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContractAdmin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ConclusionDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ConclusionDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValidityDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValidityDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpirationDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Client.FirstName) @Html.DisplayFor(model => model.Client.LastName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Smazat" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-close-white">Zpět</a>
    </form>
</div>

Views/Contracts/Details.cshtml
@model Contract_Administrator.Models.Contract

@{
    ViewData["Title"] = "Podrobnosti smlouvy";
}

<div class="row">
    <div class="col-lg">
        <h1>Smlouva @Html.DisplayFor(model => model.RegistrationNumber)</h1>
        <h4>Podrobnosti</h4>
    </div>
    <a asp-action="Index" class="col-lg-auto d-none d-lg-flex">Zpět na přehled</a>
    <hr />
</div>

<div>
    <dl class="row">
        <dt class="my-2">
            <a href="@Model.File" target="_blank" class="btn btn-secondary btn-outline-secondary">Zobrazit smlouvu</a>
        </dt>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegistrationNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Institution)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Institution)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContractAdmin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContractAdmin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ConclusionDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ConclusionDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValidityDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValidityDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpirationDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Clients" asp-action="Details" asp-route-id="@Model.ClientId">
                <div>@Html.DisplayFor(model => model.Client.FirstName) @Html.DisplayFor(model => model.Client.LastName)</div>
            </a>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContractAdviser)
        </dt>
        <dd class="col-sm-10">
            @foreach (var item in Model.ContractAdviser)
            {
                <a asp-controller="Advisers" asp-action="Details" asp-route-id="@item.Adviser.Id">
                   @item.Adviser.FirstName @item.Adviser.LastName
                </a>
                if (item.IsAdmin)
                {
                    <span> (správce smlouvy)</span>
                }
                <br />
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-secondary btn-outline-secondary">Upravit</a>
    <a asp-action="Index" class="btn btn-close-white">Zpět</a>
</div>

Views/Contracts/Edit.cshtml
@model Contract_Administrator.ViewModels.ContractViewModel

@{
    ViewData["Title"] = "Změna smlouvy";
}

<div class="row">
    <div class="col-lg">
        <h1>Smlouva - změna</h1>
    </div>
    <a asp-action="Index" class="col-lg-auto d-none d-lg-flex">Zpět na přehled</a>
    <hr />
</div>

<div class="row">
    <form asp-action="Edit">
        <div asp-validation-summary="All" class="text-danger"></div>
        <input type="hidden" asp-for="Contract.Id" />
        <div class="row">
            <div class="form-group col-lg-6 my-3">
                <label asp-for="Contract.RegistrationNumber" class="control-label"></label>
                <input asp-for="Contract.RegistrationNumber" class="form-control" />
                <span asp-validation-for="Contract.RegistrationNumber" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-6 my-3">
                <label asp-for="Contract.Institution" class="control-label"></label>
                <input asp-for="Contract.Institution" class="form-control" />
                <span asp-validation-for="Contract.Institution" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-lg-6 my-3">
                <label asp-for="Contract.ConclusionDate" class="control-label"></label>
                <input asp-for="Contract.ConclusionDate" class="form-control" />
                <span asp-validation-for="Contract.ConclusionDate" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-6 my-3">
                <label asp-for="Contract.ValidityDate" class="control-label"></label>
                <input asp-for="Contract.ValidityDate" class="form-control" />
                <span asp-validation-for="Contract.ValidityDate" class="text-danger"></span>
            </div>

        </div>
        <div class="row">
            <div class="form-group col-lg-6 my-3">
                <label asp-for="Contract.ExpirationDate" class="control-label"></label>
                <input asp-for="Contract.ExpirationDate" class="form-control" />
                <span asp-validation-for="Contract.ExpirationDate" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-6 my-3">
                <label asp-for="Contract.ClientId" class="control-label"></label>
                <select asp-for="Contract.ClientId" class="form-control" asp-items="Model.Clients">
                    <option>-- Nevybráno --</option>
                </select>
                <span asp-validation-for="Contract.ClientId" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-lg-6 my-3">
                <label asp-for="Contract.ContractAdmin" class="control-label"></label>
                <select asp-for="Contract.ContractAdmin" class="form-control" asp-items="Model.ContractAdmin">
                    <option>-- Nevybráno --</option>
                </select>
                <span asp-validation-for="Contract.ContractAdmin" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-6 my-3">
                <label asp-for="Contract.AdviserId" class="control-label"></label>
                <select asp-for="Contract.AdviserId" class="form-control" asp-items="Model.Advisers"></select>
                <span asp-validation-for="Contract.AdviserId" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-lg-6 my-3">
                <label asp-for="Contract.File" class="control-label"></label>
                <input asp-for="Contract.File" class="form-control" />
                <span asp-validation-for="Contract.File" class="text-danger"></span>

            </div>
        </div>
        <div class="row">
            <div class="form-group my-3 col-lg-12">
                <input type="submit" value="Změnit smlouvu" class="btn btn-primary text-light" />
                <a asp-action="Index" class="btn btn-close-white">Zpět</a>
            </div>
        </div>
    </form>
</div>